export const USER_EMAIL = 'USER_EMAIL';

export const MEAL_CATEGORIE = 'MEAL_CATEGORIE';
export const MEAL_CATEGORIE_SUCCESS = 'MEAL_CATEGORIE_SUCCESS';
export const MEAL_CATEGORIE_ERROR = 'MEAL_CATEGORIE_ERROR';

export const MEAL = 'MEAL';
export const MEAL_SUCCESS = 'MEAL_SUCCESS';
export const MEAL_ERROR = 'MEAL_ERROR';
