export const USER_EMAIL = 'USER_EMAIL';

export const RECIPE = 'REPICE';
export const RECIPE_SUCCESS = 'RECIPE_SUCCESS';
export const RECIPE_ERROR = 'RECIPE_ERROR';

export const COCKTAIL = 'COCKTAIL';
export const COCKTAIL_SUCCESS = 'COCKTAIL_SUCCESS';
export const COCKTAIL_ERROR = 'COCKTAIL_ERROR';

export const MEALS_CATEGORIES = 'MEALS_CATEGORIES';
export const MEALS_CATEGORIES_SUCCESS = 'MEALS_CATEGORIES_SUCCESS';
export const MEALS_CATEGORIES_ERROR = 'MEALS_CATEGORIES_ERROR';

export const MEALS = 'MEALS';
export const MEALS_SUCCESS = 'MEALS_SUCCESS';
export const MEALS_ERROR = 'MEALS_ERROR';

export const MEALS_FILTERED_CATEGORY = 'MEALS_FILTERED_CATEGORY';
export const MEALS_FILTERED_CATEGORY_SUCCESS = 'MEALS_FILTERED_CATEGORY_SUCCESS';
export const MEALS_FILTERED_CATEGORY_ERROR = 'MEALS_FILTERED_CATEGORY_ERROR';

export const DRINKS_CATEGORIES = 'DRINKS_CATEGORIES';
export const DRINKS_CATEGORIES_SUCCESS = 'DRINKS_CATEGORIES_SUCCESS';
export const DRINKS_CATEGORIES_ERROR = 'DRINKS_CATEGORIES_ERROR';

export const DRINKS = 'DRINKS';
export const DRINKS_SUCCESS = 'DRINKS_SUCCESS';
export const DRINKS_ERROR = 'DRINKS_ERROR';

export const DRINKS_FILTERED_CATEGORY = 'DRINKS_FILTERED_CATEGORY';
export const DRINKS_FILTERED_CATEGORY_SUCCESS = 'DRINKS_FILTERED_CATEGORY_SUCCESS';
export const DRINKS_FILTERED_CATEGORY_ERROR = 'DRINKS_FILTERED_CATEGORY_ERROR';

export const SEARCH_INGREDIENT_MEALS = 'SEARCH_INGREDIENT_MEALS';
export const SEARCH_INGREDIENT_MEALS_SUCCESS = 'SEARCH_INGREDIENT_MEALS_SUCCESS';
export const SEARCH_INGREDIENT_MEALS_ERROR = 'SEARCH_INGREDIENT_MEALS_ERROR';

export const SEARCH_NOME_MEALS = 'SEARCH_NOME_MEALS';
export const SEARCH_NOME_MEALS_SUCCESS = 'SEARCH_NOME_MEALS_SUCCESS';
export const SEARCH_NOME_MEALS_ERROR = 'SEARCH_NOME_MEALS_ERROR';

export const SEARCH_LETTER_MEALS = 'SEARCH_LETTER_MEALS';
export const SEARCH_LETTER_MEALS_SUCCESS = 'SEARCH_LETTER_MEALS_SUCCESS';
export const SEARCH_LETTER_MEALS_ERROR = 'SEARCH_LETTER_MEALS_ERROR';

export const SEARCH_INGREDIENT_DRINKS = 'SEARCH_INGREDIENT_DRINKS';
export const SEARCH_INGREDIENT_DRINKS_SUCCESS = 'SEARCH_INGREDIENT_DRINKS_SUCCESS';
export const SEARCH_INGREDIENT_DRINKS_ERROR = 'SEARCH_INGREDIENT_DRINKS_ERROR';

export const SEARCH_NOME_DRINKS = 'SEARCH_NOME_DRINKS';
export const SEARCH_NOME_DRINKS_SUCCESS = 'SEARCH_NOME_DRINKS_SUCCESS';
export const SEARCH_NOME_DRINKS_ERROR = 'SEARCH_NOME_DRINKS_ERROR';

export const SEARCH_LETTER_DRINKS = 'SEARCH_LETTER_DRINKS';
export const SEARCH_LETTER_DRINKS_SUCCESS = 'SEARCH_LETTER_DRINKS_SUCCESS';
export const SEARCH_LETTER_DRINKS_ERROR = 'SEARCH_LETTER_DRINKS_ERROR';
