export const ADD_FOODS = 'ADD_FOODS';
export const ADD_DRINKS = 'ADD_DRINKS';
export const ADD_DRINKS_CATEGORIES = 'ADD_DRINKS_CATEGORIES';
export const ADD_FOODS_CATEGORIES = 'ADD_FOODS_CATEGORIES';
export const ADD_MEAL_DETAIL = 'ADD_MEAL_DETAIL';
