export const USER_EMAIL = 'USER_EMAIL';

export const MEALS_CATEGORIES = 'MEALS_CATEGORIES';
export const MEALS_CATEGORIES_SUCCESS = 'MEALS_CATEGORIES_SUCCESS';
export const MEALS_CATEGORIES_ERROR = 'MEALS_CATEGORIES_ERROR';

export const MEALS = 'MEALS';
export const MEALS_SUCCESS = 'MEALS_SUCCESS';
export const MEALS_ERROR = 'MEALS_ERROR';

export const DRINKS_CATEGORIES = 'DRINKS_CATEGORIES';
export const DRINKS_CATEGORIES_SUCCESS = 'DRINKS_CATEGORIES_SUCCESS';
export const DRINKS_CATEGORIES_ERROR = 'DRINKS_CATEGORIES_ERROR';

export const DRINKS = 'DRINKS';
export const DRINKS_SUCCESS = 'DRINKS_SUCCESS';
export const DRINKS_ERROR = 'DRINKS_ERROR';
